"""V0021 unit tests — the assertions the golden ladder structurally cannot make.

`test_version_migration_golden._walk_relative` compares the set of relative PATHS.
Measured, a bare-directory-move demotion (no minted group node) differs from the
correct shape by exactly ONE path, `{member}/zarr.json`, while producing a tree whose
every data node is unreachable. One file is the ladder's entire margin, and it drops
to zero if a fixture is generated by broken code. Everything below is structural or
value-level for that reason.
"""

from __future__ import annotations

import json
import shutil
from pathlib import Path

import numpy as np
import pytest
import xarray as xr

from hhemt.version_migration import runner

FIXTURE_ROOT = Path(__file__).parent / "fixtures" / "legacy_layouts"


def _cfg_paths(fixture_dir: Path) -> dict[str, Path]:
    return {
        "system": fixture_dir / "cached_configs" / "system.yaml",
        "analysis": fixture_dir / "cached_configs" / "analysis.yaml",
    }


@pytest.fixture
def migrated(tmp_path: Path) -> Path:
    work = tmp_path / "v20"
    shutil.copytree(FIXTURE_ROOT / "v20", work)
    runner.run_migration(work, target=21, apply=True, cfg_paths=_cfg_paths(work))
    return work


def _nodes(store: Path, *, consolidated: bool) -> list[str]:
    tree = xr.open_datatree(store, engine="zarr", consolidated=consolidated, chunks={})
    return sorted(path for path, _ in tree.subtree_with_keys)


def test_store_is_renamed_to_the_experiment_tree(migrated: Path) -> None:
    assert (migrated / "experiment_datatree.zarr").is_dir()
    assert not (migrated / "analysis_datatree.zarr").exists()


def test_both_read_modes_agree_and_the_member_node_is_reachable(migrated: Path) -> None:
    """The load-bearing assertion. A bare directory move passes a path-set check and
    fails HERE: it yields ['.', 'parameters'] under both flags, so every data node is
    gone while the file set is one entry short."""
    store = migrated / "experiment_datatree.zarr"
    lazy = _nodes(store, consolidated=False)
    consolidated = _nodes(store, consolidated=True)
    assert lazy == consolidated, "consolidated and unconsolidated reads disagree — stale root zarr.json"
    member = next(n for n in lazy if n.startswith("member_"))
    assert f"{member}/tritonswmm/summary" in lazy
    assert "parameters" in lazy


def test_root_attrs_and_leaf_values_survive_the_demotion(migrated: Path) -> None:
    before = xr.open_datatree(
        FIXTURE_ROOT / "v20" / "analysis_datatree.zarr", engine="zarr", consolidated=False, chunks={}
    )
    after = xr.open_datatree(migrated / "experiment_datatree.zarr", engine="zarr", consolidated=False, chunks={})
    for key in ("Conventions", "analysis_id"):
        assert after.attrs[key] == before.attrs[key]
    member = next(p for p, _ in after.subtree_with_keys if p.startswith("member_") and "/" not in p)
    assert np.array_equal(
        after[f"{member}/tritonswmm/summary"].dataset.depth.values,
        before["tritonswmm/summary"].dataset.depth.values,
        equal_nan=True,
    )


def test_parameters_carries_an_object_dtype_column(migrated: Path) -> None:
    """Not decoration: it is what makes `chunks={}` unconditionally correct downstream
    once the filename stops discriminating experiment shapes."""
    tree = xr.open_datatree(migrated / "experiment_datatree.zarr", engine="zarr", consolidated=False, chunks={})
    dtypes = {str(v.dtype) for v in tree["parameters"].dataset.variables.values()}
    assert "object" in dtypes


def test_reapplying_the_migration_is_a_no_op(migrated: Path) -> None:
    before = {str(p.relative_to(migrated)) for p in migrated.rglob("*")}
    runner.run_migration(migrated, target=21, apply=True, cfg_paths=_cfg_paths(migrated))
    assert {str(p.relative_to(migrated)) for p in migrated.rglob("*")} == before


def test_provenance_is_repointed_in_BOTH_the_sidecar_and_the_embedded_core(tmp_path: Path) -> None:
    """The provenance is dual-written. A sidecar-only repair leaves a stale `@id` and
    `schemaVersion` inside the renamed store, which no sidecar check reaches.

    The crate is built BY THE EMITTER, never hand-planted. A planted
    `{"@id": "analysis_datatree.zarr"}` is the shape the code expects rather than the
    shape `ro-crate-py` produces — `Dataset.format_id` returns `identifier.rstrip("/") + "/"`
    — so a planted fixture passes against a `_repoint` that matches nothing.
    """
    work = tmp_path / "v20"
    shutil.copytree(FIXTURE_ROOT / "v20", work)
    store = work / "analysis_datatree.zarr"
    # The input is EMITTED, never hand-written. A planted `{"@id": "analysis_datatree.zarr"}`
    # omits the trailing slash ro-crate-py adds to every Dataset @id, so a test built that
    # way passes against a _repoint that matches nothing -- which is exactly how the
    # unslashed comparison survived its first review.
    from types import SimpleNamespace

    from hhemt import metadata

    _crate = metadata.build_analysis_crate(
        analysis_id="a1",
        system_id="s1",
        layout_version=20,
        toolkit_git_sha="deadbeef",
        code_repository="https://example/repo",
        cfg_case=SimpleNamespace(case_name="norfolk", description="t", manifest={}),
        sif_spec=None,
        consolidated_zarr_relpath="analysis_datatree.zarr",
        input_parts=[],
        sub_dataset_relpaths=["members/member_1/"],
    )
    crate = json.loads(metadata.canonical_jsonld(_crate))
    _core = metadata.partition_core_vs_sidecar(crate)
    crate_core = _core[0] if isinstance(_core, tuple) else _core
    assert any(
        e.get("@id") == "analysis_datatree.zarr/" for e in crate["@graph"]
    ), "emitter no longer slash-normalizes the store @id; this test's premise has moved"
    (work / "ro-crate-metadata.json").write_text(json.dumps(crate, indent=2))
    meta = json.loads((store / "zarr.json").read_text())
    meta.setdefault("attributes", {})["ro_crate_metadata"] = json.dumps(
        crate_core, separators=(",", ":"), sort_keys=True
    )
    (store / "zarr.json").write_text(json.dumps(meta, indent=2))

    runner.run_migration(work, target=21, apply=True, cfg_paths=_cfg_paths(work))

    sidecar = json.loads((work / "ro-crate-metadata.json").read_text())
    embedded = json.loads(
        json.loads((work / "experiment_datatree.zarr" / "zarr.json").read_text())["attributes"]["ro_crate_metadata"]
    )
    for doc, label in ((sidecar, "sidecar"), (embedded, "embedded core")):
        stems = [str(e.get("@id")).rstrip("/") for e in doc["@graph"]]
        assert "experiment_datatree.zarr" in stems, f"{label} still names the retired store"
        assert "analysis_datatree.zarr" not in stems, f"{label} retains the retired store id"
        root = next(e for e in doc["@graph"] if e["@id"] == "./")
        assert root["schemaVersion"] == "21", f"{label} carries a stale schemaVersion"
        hp = [str(r.get("@id")).rstrip("/") for r in (root.get("hasPart") or []) if isinstance(r, dict)]
        assert "experiment_datatree.zarr" in hp, f"{label} hasPart still names the retired store"
        assert "analysis_datatree.zarr" not in hp, f"{label} hasPart retains the retired store id"
