"""The column-set verdict reaches `df_status`, and a homogeneous analysis does not render it.

WHAT THIS PINS AND WHY IT IS NOT OBVIOUS. The stored
`perf_column_set_across_allocations` coordinate is a SENTENCE, and its uniform form embeds
`len(df_labels)` -- one entry per PARSED `performance{N}.txt` CHECKPOINT file, not one per
allocation. So two members that agree perfectly on their column set carry DIFFERENT stored
strings whenever they ran different numbers of reporting steps, or whenever one lost a
checkpoint to a kill or a malformed-parse skip. Surfacing the raw string in `df_status`
would therefore make `nunique(dropna=False)` equal 2 on an analysis with no heterogeneity
anywhere, and the appendix's constant-column suppression -- the only thing keeping this
column off a homogeneous analysis -- would stop firing.

`column_set_verdict` is the collapse that fixes it, and the test that matters here is
`test_the_appendix_hides_the_column_when_members_differ_only_in_checkpoint_count`: it is
the exact case that would be reintroduced by a later edit routing the raw coordinate
through instead.

MEASURED TWO-ARM DIFFERENTIAL, pasted rather than predicted. The invariant is "the column
renders exactly when members disagree about their COLUMN SET, never when they merely
disagree about their checkpoint count". Arm (a), violating input -- `column_set_verdict`
edited to return the RAW stored string: `6 failed, 8 passed`, and the failure that matters
is

    AssertionError: A homogeneous analysis rendered the column-set column. Either the
    mapping stopped collapsing the uniform findings, or hide_constant_columns stopped
    defaulting True.

`test_the_appendix_shows_the_column_when_a_member_is_genuinely_heterogeneous` is among the
seven that still PASS under that arm, which is the point: the suite discriminates on the
collapse rather than on the column merely existing, so a mapping that hid the column
outright would not satisfy it. Arm (b), a differently-positioned SATISFYING input -- three
members at checkpoint counts 1, 2 and 5 rather than the two the hide test uses, and an
all-historical analysis carrying no coordinate at all: no finding in either, the column
stays hidden.

THE ZARR IS OUT OF SCOPE HERE. Nothing in this file asserts on the stored coordinate; the
stamp, its string form and its carriage into the consolidated tree are accepted work and
are pinned by `tests/test_perf_column_set_guard.py`.
"""

from __future__ import annotations

import numpy as np
import pandas as pd
import pytest
import xarray as xr

from hhemt.analysis import PERF_VARS, _column_set_cell, _perf_row_from_dataset
from hhemt.config.report import DEFAULT_REPORT_CONFIG
from hhemt.process_simulation import (
    NAME_SET_UNKNOWN,
    PERF_COLUMN_SET_COORD,
    UNIFORM_COLUMN_SET_VERDICT,
    column_set_verdict,
    describe_allocation_column_sets,
)
from hhemt.report_renderers.scenario_status_appendix import _build_tabulator_html

_COLS = ("Total", "Compute", "MPI")


def _uniform_finding(n_checkpoints: int) -> str:
    """A real no-heterogeneity finding over `n_checkpoints` files with ONE column set.

    Generated by the production function rather than hand-written, deliberately: the whole
    defect this file exists for was invisible to a hand-written input string, because an
    author writing the input also writes in the count they expect.
    """
    labels = [f"performance{i}.txt" for i in range(n_checkpoints)]
    return describe_allocation_column_sets(labels, [_COLS] * n_checkpoints)


def _heterogeneous_finding() -> str:
    return describe_allocation_column_sets(
        ["performance0.txt", "performance1.txt"],
        [_COLS, _COLS[:2]],
    )


def _summary_ds(finding: str | None) -> xr.Dataset:
    """A per-member performance SUMMARY in the shape `_perf_row_from_dataset` receives."""
    ds = xr.Dataset(
        {v: ("event_iloc", np.array([1.0])) for v in PERF_VARS},
        coords={"event_iloc": [0]},
    )
    if finding is not None:
        ds = ds.assign_coords({PERF_COLUMN_SET_COORD: ("event_iloc", [finding])})
    return ds


def _appendix_html(findings: list[str | None]) -> str:
    """Render the real appendix over a minimal frame carrying one row per finding."""
    df = pd.DataFrame(
        {
            "event_iloc": list(range(len(findings))),
            "model_type": ["tritonswmm"] * len(findings),
            "perf_Total": [float(i + 1) for i in range(len(findings))],
            PERF_COLUMN_SET_COORD: [column_set_verdict(f) for f in findings],
        }
    )
    return _build_tabulator_html(
        df,
        DEFAULT_REPORT_CONFIG,
        csv_present=True,
        analysis_id="test-analysis",
        weather_event_indices=[],
    )


def test_the_production_finding_really_does_vary_with_the_checkpoint_count():
    """The premise. Without this the collapse tests below would be vacuous."""
    one, two, five = _uniform_finding(1), _uniform_finding(2), _uniform_finding(5)
    assert one != two != five and one != five, (
        "The uniform finding is expected to embed the checkpoint count. If these are equal, "
        "the producer changed and column_set_verdict's whole reason for existing needs "
        "re-deriving rather than the test relaxing."
    )
    assert pd.Series([one, two, five]).nunique(dropna=False) == 3


@pytest.mark.parametrize("counts", [(1, 2), (1, 2, 5), (3, 144)])
def test_uniform_findings_collapse_to_one_verdict_whatever_the_checkpoint_counts(counts):
    verdicts = [column_set_verdict(_uniform_finding(n)) for n in counts]
    assert set(verdicts) == {UNIFORM_COLUMN_SET_VERDICT}
    assert pd.Series(verdicts).nunique(dropna=False) == 1, (
        "nunique must reach 1, because that -- not string equality -- is the property the "
        "appendix's hide predicate actually reads."
    )


def test_a_heterogeneous_finding_passes_through_verbatim():
    finding = _heterogeneous_finding()
    assert finding.startswith("HETEROGENEOUS")
    assert column_set_verdict(finding) == finding, (
        "The heterogeneous sentence names which files are short and what it costs the "
        "reader; flattening it would strand an appendix reader with no route to the "
        "statement."
    )


def test_an_absent_finding_maps_to_none_and_not_to_a_sentinel():
    assert column_set_verdict(None) is None


def test_the_unknown_sentinel_passes_through_and_is_not_laundered_into_uniform():
    assert column_set_verdict(NAME_SET_UNKNOWN) == NAME_SET_UNKNOWN
    assert column_set_verdict(NAME_SET_UNKNOWN) != UNIFORM_COLUMN_SET_VERDICT


def test_the_cell_carries_the_verdict_when_the_member_has_the_coordinate():
    assert _column_set_cell(_summary_ds(_uniform_finding(4))) == {PERF_COLUMN_SET_COORD: UNIFORM_COLUMN_SET_VERDICT}


def test_the_cell_does_not_raise_on_a_member_that_predates_the_coordinate():
    """A tree consolidated before the coordinate shipped must still build a status row.

    The guarded read is the same shape PERF_VARS membership already uses; an unguarded
    subscript here would raise KeyError inside the df_status row loop and fail the whole
    status frame for the analysis rather than blanking one cell.
    """
    assert _column_set_cell(_summary_ds(None)) == {PERF_COLUMN_SET_COORD: None}


def test_the_perf_row_helper_keeps_its_pinned_float_only_contract():
    """The cell is a SIBLING of _perf_row_from_dataset, never a widening of it.

    tests/test_perf_column_split.py pins that helper's rows as exactly the PERF_VARS key
    set with float-or-None values. Folding a string verdict in would have reddened three
    correct assertions; this asserts the separation directly so a later refactor that
    merges the two is caught here as well as there.
    """
    row = _perf_row_from_dataset(_summary_ds(_uniform_finding(4)))
    assert set(row) == {f"perf_{v}" for v in PERF_VARS}
    assert PERF_COLUMN_SET_COORD not in row


def test_the_appendix_hides_the_column_when_members_differ_only_in_checkpoint_count():
    """THE CASE THIS FILE EXISTS FOR.

    Two members, identical column sets, DIFFERENT checkpoint counts -- an analysis with no
    heterogeneity anywhere. The rendered appendix must not carry the column. Against a
    mapping that routes the RAW stored string through, this is the assertion that goes red.
    """
    html = _appendix_html([_uniform_finding(2), _uniform_finding(3)])
    assert PERF_COLUMN_SET_COORD not in html, (
        "A homogeneous analysis rendered the column-set column. Either the mapping stopped "
        "collapsing the uniform findings, or hide_constant_columns stopped defaulting True."
    )


def test_the_appendix_hides_the_column_across_three_differently_spaced_members():
    """Arm (b) of the differential: a DIFFERENT satisfying position, still hidden."""
    html = _appendix_html([_uniform_finding(1), _uniform_finding(2), _uniform_finding(5)])
    assert PERF_COLUMN_SET_COORD not in html


def test_the_appendix_shows_the_column_when_a_member_is_genuinely_heterogeneous():
    html = _appendix_html([_uniform_finding(2), _heterogeneous_finding()])
    assert PERF_COLUMN_SET_COORD in html, (
        "Real heterogeneity must reach the reader; a mapping that hid this too would "
        "satisfy the hide test above by deleting the signal rather than by collapsing it."
    )


def test_the_appendix_hides_the_column_on_an_all_historical_analysis():
    html = _appendix_html([None, None])
    assert PERF_COLUMN_SET_COORD not in html
