"""Consolidated-zarr-only deletion runner for the SLURM-offloaded reprocess
delete (R8). Invoked by the analysis-level ``delete_reprocess_consolidation``
rule in ``Snakefile.reprocess_delete`` (the master dir for sensitivity, the
analysis dir for non-sensitivity). Under D-scope Option C the per-SUB
``analysis_datatree.zarr`` is deleted by ``delete_subanalysis_reprocess_runner``
(item 5b), NOT by this runner. Deletes ONLY ``analysis_datatree.zarr`` +
(sensitivity master) ``sensitivity_datatree.zarr`` — the HEAVY component. Does
NOT touch report/plots/_status/_generated (regenerated by the reprocess run).
Distinct from ``delete_consolidation_runner`` (whole analysis-level artifact set + _status)."""

from __future__ import annotations

import argparse
import datetime
import json
import logging
import os
import sys
from pathlib import Path

from TRITON_SWMM_toolkit.status_flags import write_status_flag
from TRITON_SWMM_toolkit.utils import fast_rmtree

logger = logging.getLogger(__name__)

# NARROW set — ONLY the consolidated zarrs. Report/plots/_status are regenerated,
# never deleted here. These two filenames are the canonical defaults
# (analysis.py:160 computes analysis_paths.analysis_datatree_zarr from the same
# "analysis_datatree.zarr" literal; the sensitivity master sets
# "sensitivity_datatree.zarr"). Hardcoded because the runner only receives
# --analysis-dir; KEEP IN SYNC if either consolidated-zarr filename ever becomes
# config-driven.
_REPROCESS_ZARR_ARTIFACTS = ["analysis_datatree.zarr", "sensitivity_datatree.zarr"]

def _parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--analysis-dir", type=Path, required=True)
    return parser.parse_args(argv)

def _write_submission_sentinel(sentinel_path: Path, *, rule_token: str, slurm_job_id: str) -> None:
    sentinel_path.parent.mkdir(parents=True, exist_ok=True)
    tmp = sentinel_path.with_suffix(".json.tmp")
    tmp.write_text(json.dumps({
        "slurm_jobid": slurm_job_id,
        "run_uuid": os.environ.get("SLURM_JOB_NAME"),
        "rule_token": rule_token,
        "submitted_at": datetime.datetime.now().isoformat(),
    }))
    os.replace(tmp, sentinel_path)

def main(argv: list[str] | None = None) -> int:
    args = _parse_args(argv)
    analysis_dir = args.analysis_dir.resolve()
    _sentinel: Path | None = None
    _slurm_jobid = os.environ.get("SLURM_JOB_ID")
    if _slurm_jobid:
        _rule_token = "delete_reprocess_consolidation"
        _sentinel = analysis_dir / "_status" / "_submitted" / f"{_rule_token}.json"
        _write_submission_sentinel(_sentinel, rule_token=_rule_token, slurm_job_id=_slurm_jobid)
    try:
        for name in _REPROCESS_ZARR_ARTIFACTS:
            path = analysis_dir / name
            if path.exists():
                print(f"[delete-reprocess-zarr] removing {path}", flush=True)
                fast_rmtree(path, analysis_dir=analysis_dir)  # PATTERN A
        flag_path = analysis_dir / "_status" / "_deleting_reprocess" / "reprocess_consolidation.flag"
        write_status_flag(flag_path, rule_name="delete_reprocess_consolidation")
        return 0
    finally:
        if _sentinel is not None:
            # EXEMPT-DU: status-flag
            _sentinel.unlink(missing_ok=True)

if __name__ == "__main__":
    sys.exit(main())
