# Auto-generated by TRITONSWMM_analysis

import os
import glob
import subprocess
from datetime import datetime as _dt
from TRITON_SWMM_toolkit.report_renderers._figure_emission import format_sources_rst as _fmt_sources_rst

try:
    from importlib.metadata import version as _pkg_version
    _toolkit_version = _pkg_version("TRITON_SWMM_toolkit")
except Exception:
    _toolkit_version = "unknown"

# Config dict consumed by report_templates/workflow_description.rst.j2
config["analysis_id"] = 'synth_multi_sim'
config["toolkit_version"] = _toolkit_version
config["n_sims"] = 3
config["is_sensitivity"] = False
config["report"] = {"generated_at": _dt.now().isoformat(timespec="seconds")}

report: "report/workflow_description.rst"

SIM_IDS = ['event_index.0', 'event_index.1', 'event_index.2']
ILOC_BY_EVENT_ID = {'event_index.0': 0, 'event_index.1': 1, 'event_index.2': 2}

rule all:
    input:
        "_status/e_consolidate_complete.flag",
        "scenario_status.csv",
        "workflow_summary.md",
        "plots/system_overview.html",
        expand("plots/per_sim/{event_id}/peak_flood_depth__evt.{event_id}.html", event_id=SIM_IDS),
        expand("plots/per_sim/{event_id}/conduit_flow__evt.{event_id}.html", event_id=SIM_IDS),
        "plots/per_analysis/summary_table.html",
        "plots/appendix/scenario_status.html",
        "plots/errors_and_warnings/validation_report.html",
        "plots/disk_utilization.html",
        "analysis_report.zip",

# onsuccess: removed — `rule export_scenario_status` (added below) now produces
# scenario_status.csv and workflow_summary.md on the success path via the
# Snakemake DAG. The previous `onsuccess:` hook fired AFTER all rules
# completed, which is too late for the renderer rules that consume the CSV.

onerror:
    # Partial-run debugging fallback: when a rule earlier in the DAG fails,
    # the export rule never fires (its input flag is absent), so this hook
    # is the only path to a diagnostic CSV. Snakemake treats `onerror:` exit
    # codes as informational — the workflow has already failed.
    shell("""
        /home/dcl3nd/miniconda3/envs/triton_swmm_toolkit/bin/python -m TRITON_SWMM_toolkit.export_scenario_status \
            --system-config /home/dcl3nd/.cache/TRITON_SWMM_toolkit/synthetic_test_runs/toolkit_06-13_2259_named-reporting-sets/synth_multi_sim/system_config.yaml \
            --analysis-config /home/dcl3nd/.cache/TRITON_SWMM_toolkit/synthetic_test_runs/toolkit_06-13_2259_named-reporting-sets/synth_multi_sim/analysis_config.yaml \
            > /home/dcl3nd/.cache/TRITON_SWMM_toolkit/synthetic_test_runs/toolkit_06-13_2259_named-reporting-sets/synth_multi_sim/synth_multi_sim/logs/export_scenario_status.log 2>&1
    """)

rule setup:
    output: "_status/a_setup_complete.flag"
    log: "/home/dcl3nd/.cache/TRITON_SWMM_toolkit/synthetic_test_runs/toolkit_06-13_2259_named-reporting-sets/synth_multi_sim/synth_multi_sim/logs/setup.log"
    conda: "/home/dcl3nd/dev/TRITON-SWMM_toolkit/.claude/worktrees/toolkit_06-13_2259_named-reporting-sets/workflow/envs/triton_swmm.yaml"
    resources:
        slurm_partition="None",
        runtime=60,
        tasks=1,
        cpus_per_task=1,
        mem_mb=12000,
        nodes=1
    shell:
        """
        /home/dcl3nd/miniconda3/envs/triton_swmm_toolkit/bin/python -m TRITON_SWMM_toolkit.setup_workflow \
            --system-config /home/dcl3nd/.cache/TRITON_SWMM_toolkit/synthetic_test_runs/toolkit_06-13_2259_named-reporting-sets/synth_multi_sim/system_config.yaml \
            --analysis-config /home/dcl3nd/.cache/TRITON_SWMM_toolkit/synthetic_test_runs/toolkit_06-13_2259_named-reporting-sets/synth_multi_sim/analysis_config.yaml \
            --process-system-inputs \
            \
            --compile-triton-swmm \
            --compile-triton-only \
            --compile-swmm \
            \
            --flag-output {output} \
            --rule-name setup \
            > {log} 2>&1
        """

rule prepare_scenario:
    input: "_status/a_setup_complete.flag"
    output: "_status/b_prepare_evt-{event_id}_complete.flag"
    log: "/home/dcl3nd/.cache/TRITON_SWMM_toolkit/synthetic_test_runs/toolkit_06-13_2259_named-reporting-sets/synth_multi_sim/synth_multi_sim/logs/sims/prepare_evt-{event_id}.log"
    conda: "/home/dcl3nd/dev/TRITON-SWMM_toolkit/.claude/worktrees/toolkit_06-13_2259_named-reporting-sets/workflow/envs/triton_swmm.yaml"
    params:
        event_iloc=lambda wildcards: ILOC_BY_EVENT_ID[wildcards.event_id],
    resources:
        slurm_partition="None",
        runtime=30,
        tasks=1,
        cpus_per_task=1,
        mem_mb=2000,
        nodes=1
    shell:
        """
        /home/dcl3nd/miniconda3/envs/triton_swmm_toolkit/bin/python -m TRITON_SWMM_toolkit.prepare_scenario_runner \
            --event-iloc {params.event_iloc} \
            --system-config /home/dcl3nd/.cache/TRITON_SWMM_toolkit/synthetic_test_runs/toolkit_06-13_2259_named-reporting-sets/synth_multi_sim/system_config.yaml \
            --analysis-config /home/dcl3nd/.cache/TRITON_SWMM_toolkit/synthetic_test_runs/toolkit_06-13_2259_named-reporting-sets/synth_multi_sim/analysis_config.yaml \
            \
            \
            --flag-output {output} \
            --rule-name prepare_scenario \
            --event-id {wildcards.event_id} \
            > {log} 2>&1
        """

rule run_triton:
    input: "_status/b_prepare_evt-{event_id}_complete.flag"
    output: "_status/c_run_triton_evt-{event_id}_complete.flag"
    log: "/home/dcl3nd/.cache/TRITON_SWMM_toolkit/synthetic_test_runs/toolkit_06-13_2259_named-reporting-sets/synth_multi_sim/synth_multi_sim/logs/sims/triton_evt-{event_id}.log"
    conda: "/home/dcl3nd/dev/TRITON-SWMM_toolkit/.claude/worktrees/toolkit_06-13_2259_named-reporting-sets/workflow/envs/triton_swmm.yaml"
    threads: 1
    params:
        event_iloc=lambda wildcards: ILOC_BY_EVENT_ID[wildcards.event_id],
    resources:
        slurm_partition="None",
        runtime=60,
        tasks=1,
        cpus_per_task=1,
        mem_mb=2000,
        nodes=1
    shell:
        """
        /home/dcl3nd/miniconda3/envs/triton_swmm_toolkit/bin/python -m TRITON_SWMM_toolkit.run_simulation_runner \
            --event-iloc {params.event_iloc} \
            --system-config /home/dcl3nd/.cache/TRITON_SWMM_toolkit/synthetic_test_runs/toolkit_06-13_2259_named-reporting-sets/synth_multi_sim/system_config.yaml \
            --analysis-config /home/dcl3nd/.cache/TRITON_SWMM_toolkit/synthetic_test_runs/toolkit_06-13_2259_named-reporting-sets/synth_multi_sim/analysis_config.yaml \
            --model-type triton \
            \
            --flag-output {output} \
            --rule-name run_triton \
            --event-id {wildcards.event_id} \
            > {log} 2>&1
        """

rule run_tritonswmm:
    input: "_status/b_prepare_evt-{event_id}_complete.flag"
    output: "_status/c_run_tritonswmm_evt-{event_id}_complete.flag"
    log: "/home/dcl3nd/.cache/TRITON_SWMM_toolkit/synthetic_test_runs/toolkit_06-13_2259_named-reporting-sets/synth_multi_sim/synth_multi_sim/logs/sims/tritonswmm_evt-{event_id}.log"
    conda: "/home/dcl3nd/dev/TRITON-SWMM_toolkit/.claude/worktrees/toolkit_06-13_2259_named-reporting-sets/workflow/envs/triton_swmm.yaml"
    threads: 1
    params:
        event_iloc=lambda wildcards: ILOC_BY_EVENT_ID[wildcards.event_id],
    resources:
        slurm_partition="None",
        runtime=60,
        tasks=1,
        cpus_per_task=1,
        mem_mb=2000,
        nodes=1
    shell:
        """
        /home/dcl3nd/miniconda3/envs/triton_swmm_toolkit/bin/python -m TRITON_SWMM_toolkit.run_simulation_runner \
            --event-iloc {params.event_iloc} \
            --system-config /home/dcl3nd/.cache/TRITON_SWMM_toolkit/synthetic_test_runs/toolkit_06-13_2259_named-reporting-sets/synth_multi_sim/system_config.yaml \
            --analysis-config /home/dcl3nd/.cache/TRITON_SWMM_toolkit/synthetic_test_runs/toolkit_06-13_2259_named-reporting-sets/synth_multi_sim/analysis_config.yaml \
            --model-type tritonswmm \
            \
            --flag-output {output} \
            --rule-name run_tritonswmm \
            --event-id {wildcards.event_id} \
            > {log} 2>&1
        """

rule run_swmm:
    input: "_status/b_prepare_evt-{event_id}_complete.flag"
    output: "_status/c_run_swmm_evt-{event_id}_complete.flag"
    log: "/home/dcl3nd/.cache/TRITON_SWMM_toolkit/synthetic_test_runs/toolkit_06-13_2259_named-reporting-sets/synth_multi_sim/synth_multi_sim/logs/sims/swmm_evt-{event_id}.log"
    conda: "/home/dcl3nd/dev/TRITON-SWMM_toolkit/.claude/worktrees/toolkit_06-13_2259_named-reporting-sets/workflow/envs/triton_swmm.yaml"
    threads: 1
    params:
        event_iloc=lambda wildcards: ILOC_BY_EVENT_ID[wildcards.event_id],
    resources:
        slurm_partition="None",
        runtime=60,
        tasks=1,
        cpus_per_task=1,
        mem_mb=2000,
        nodes=1
    shell:
        """
        /home/dcl3nd/miniconda3/envs/triton_swmm_toolkit/bin/python -m TRITON_SWMM_toolkit.run_simulation_runner \
            --event-iloc {params.event_iloc} \
            --system-config /home/dcl3nd/.cache/TRITON_SWMM_toolkit/synthetic_test_runs/toolkit_06-13_2259_named-reporting-sets/synth_multi_sim/system_config.yaml \
            --analysis-config /home/dcl3nd/.cache/TRITON_SWMM_toolkit/synthetic_test_runs/toolkit_06-13_2259_named-reporting-sets/synth_multi_sim/analysis_config.yaml \
            --model-type swmm \
            \
            --flag-output {output} \
            --rule-name run_swmm \
            --event-id {wildcards.event_id} \
            > {log} 2>&1
        """

rule process_triton:
    input: "_status/c_run_triton_evt-{event_id}_complete.flag"
    output: "_status/d_process_triton_evt-{event_id}_complete.flag"
    log: "/home/dcl3nd/.cache/TRITON_SWMM_toolkit/synthetic_test_runs/toolkit_06-13_2259_named-reporting-sets/synth_multi_sim/synth_multi_sim/logs/sims/process_triton_evt-{event_id}.log"
    group: "process_evt_{event_id}"
    conda: "/home/dcl3nd/dev/TRITON-SWMM_toolkit/.claude/worktrees/toolkit_06-13_2259_named-reporting-sets/workflow/envs/triton_swmm.yaml"
    params:
        event_iloc=lambda wildcards: ILOC_BY_EVENT_ID[wildcards.event_id],
    resources:
        slurm_partition="None",
        runtime=120,
        tasks=1,
        cpus_per_task=2,
        mem_mb=12000,
        nodes=1
    shell:
        """
        /home/dcl3nd/miniconda3/envs/triton_swmm_toolkit/bin/python -m TRITON_SWMM_toolkit.process_timeseries_runner \
            --event-iloc {params.event_iloc} \
            --system-config /home/dcl3nd/.cache/TRITON_SWMM_toolkit/synthetic_test_runs/toolkit_06-13_2259_named-reporting-sets/synth_multi_sim/system_config.yaml \
            --analysis-config /home/dcl3nd/.cache/TRITON_SWMM_toolkit/synthetic_test_runs/toolkit_06-13_2259_named-reporting-sets/synth_multi_sim/analysis_config.yaml \
            --model-type triton \
            --which TRITON \
            \
            --compression-level 5 \
            --flag-output {output} \
            --rule-name process_triton \
            --event-id {wildcards.event_id} \
            > {log} 2>&1
        """

rule process_tritonswmm:
    input: "_status/c_run_tritonswmm_evt-{event_id}_complete.flag"
    output: "_status/d_process_tritonswmm_evt-{event_id}_complete.flag"
    log: "/home/dcl3nd/.cache/TRITON_SWMM_toolkit/synthetic_test_runs/toolkit_06-13_2259_named-reporting-sets/synth_multi_sim/synth_multi_sim/logs/sims/process_tritonswmm_evt-{event_id}.log"
    group: "process_evt_{event_id}"
    conda: "/home/dcl3nd/dev/TRITON-SWMM_toolkit/.claude/worktrees/toolkit_06-13_2259_named-reporting-sets/workflow/envs/triton_swmm.yaml"
    params:
        event_iloc=lambda wildcards: ILOC_BY_EVENT_ID[wildcards.event_id],
    resources:
        slurm_partition="None",
        runtime=120,
        tasks=1,
        cpus_per_task=2,
        mem_mb=12000,
        nodes=1
    shell:
        """
        /home/dcl3nd/miniconda3/envs/triton_swmm_toolkit/bin/python -m TRITON_SWMM_toolkit.process_timeseries_runner \
            --event-iloc {params.event_iloc} \
            --system-config /home/dcl3nd/.cache/TRITON_SWMM_toolkit/synthetic_test_runs/toolkit_06-13_2259_named-reporting-sets/synth_multi_sim/system_config.yaml \
            --analysis-config /home/dcl3nd/.cache/TRITON_SWMM_toolkit/synthetic_test_runs/toolkit_06-13_2259_named-reporting-sets/synth_multi_sim/analysis_config.yaml \
            --model-type tritonswmm \
            --which both \
            \
            --compression-level 5 \
            --flag-output {output} \
            --rule-name process_tritonswmm \
            --event-id {wildcards.event_id} \
            > {log} 2>&1
        """

rule process_swmm:
    input: "_status/c_run_swmm_evt-{event_id}_complete.flag"
    output: "_status/d_process_swmm_evt-{event_id}_complete.flag"
    log: "/home/dcl3nd/.cache/TRITON_SWMM_toolkit/synthetic_test_runs/toolkit_06-13_2259_named-reporting-sets/synth_multi_sim/synth_multi_sim/logs/sims/process_swmm_evt-{event_id}.log"
    group: "process_evt_{event_id}"
    conda: "/home/dcl3nd/dev/TRITON-SWMM_toolkit/.claude/worktrees/toolkit_06-13_2259_named-reporting-sets/workflow/envs/triton_swmm.yaml"
    params:
        event_iloc=lambda wildcards: ILOC_BY_EVENT_ID[wildcards.event_id],
    resources:
        slurm_partition="None",
        runtime=120,
        tasks=1,
        cpus_per_task=2,
        mem_mb=12000,
        nodes=1
    shell:
        """
        /home/dcl3nd/miniconda3/envs/triton_swmm_toolkit/bin/python -m TRITON_SWMM_toolkit.process_timeseries_runner \
            --event-iloc {params.event_iloc} \
            --system-config /home/dcl3nd/.cache/TRITON_SWMM_toolkit/synthetic_test_runs/toolkit_06-13_2259_named-reporting-sets/synth_multi_sim/system_config.yaml \
            --analysis-config /home/dcl3nd/.cache/TRITON_SWMM_toolkit/synthetic_test_runs/toolkit_06-13_2259_named-reporting-sets/synth_multi_sim/analysis_config.yaml \
            --model-type swmm \
            --which SWMM \
            \
            --compression-level 5 \
            --flag-output {output} \
            --rule-name process_swmm \
            --event-id {wildcards.event_id} \
            > {log} 2>&1
        """

rule consolidate_scenario:
    input: "_status/d_process_triton_evt-{event_id}_complete.flag", "_status/d_process_tritonswmm_evt-{event_id}_complete.flag", "_status/d_process_swmm_evt-{event_id}_complete.flag"
    output:
        flag="_status/f_consolidate_scenario_evt-{event_id}_complete.flag",
        du_sentinel="sims/{event_id}/_status/_du.json",
    log: "/home/dcl3nd/.cache/TRITON_SWMM_toolkit/synthetic_test_runs/toolkit_06-13_2259_named-reporting-sets/synth_multi_sim/synth_multi_sim/logs/sims/consolidate_scenario_evt-{event_id}.log"
    group: "process_evt_{event_id}"
    conda: "/home/dcl3nd/dev/TRITON-SWMM_toolkit/.claude/worktrees/toolkit_06-13_2259_named-reporting-sets/workflow/envs/triton_swmm.yaml"
    resources:
        slurm_partition="None",
        runtime=10,
        tasks=1,
        cpus_per_task=1,
        mem_mb=2048,
        nodes=1
    shell:
        """
        /home/dcl3nd/miniconda3/envs/triton_swmm_toolkit/bin/python -m TRITON_SWMM_toolkit.consolidate_workflow \
            --system-config /home/dcl3nd/.cache/TRITON_SWMM_toolkit/synthetic_test_runs/toolkit_06-13_2259_named-reporting-sets/synth_multi_sim/system_config.yaml \
            --analysis-config /home/dcl3nd/.cache/TRITON_SWMM_toolkit/synthetic_test_runs/toolkit_06-13_2259_named-reporting-sets/synth_multi_sim/analysis_config.yaml \
            --compression-level 5 \
            --flag-output {output.flag} \
            --rule-name consolidate_scenario \
            --event-id {wildcards.event_id} \
            > {log} 2>&1
        """

rule consolidate:
    input: expand("_status/f_consolidate_scenario_evt-{event_id}_complete.flag", event_id=SIM_IDS)
    output: "_status/e_consolidate_complete.flag"
    log: "/home/dcl3nd/.cache/TRITON_SWMM_toolkit/synthetic_test_runs/toolkit_06-13_2259_named-reporting-sets/synth_multi_sim/synth_multi_sim/logs/consolidate.log"
    conda: "/home/dcl3nd/dev/TRITON-SWMM_toolkit/.claude/worktrees/toolkit_06-13_2259_named-reporting-sets/workflow/envs/triton_swmm.yaml"
    resources:
        slurm_partition="None",
        runtime=30,
        tasks=1,
        cpus_per_task=2,
        mem_mb=12000,
        nodes=1
    shell:
        """
        /home/dcl3nd/miniconda3/envs/triton_swmm_toolkit/bin/python -m TRITON_SWMM_toolkit.consolidate_workflow \
            --system-config /home/dcl3nd/.cache/TRITON_SWMM_toolkit/synthetic_test_runs/toolkit_06-13_2259_named-reporting-sets/synth_multi_sim/system_config.yaml \
            --analysis-config /home/dcl3nd/.cache/TRITON_SWMM_toolkit/synthetic_test_runs/toolkit_06-13_2259_named-reporting-sets/synth_multi_sim/analysis_config.yaml \
            --compression-level 5 \
            \
            --which TRITON \
            --flag-output {output} \
            --rule-name consolidate \
            > {log} 2>&1
        """

rule plot_system_overview:
    input:
        consolidated = "_status/e_consolidate_complete.flag",
    output:
        report(
            "plots/system_overview.html",
            caption="report/captions/system_map.rst",
            category="System Information",
            labels={"figure": "System map"},
        )
    params:
        source_paths = [{'path': '../elevation_10.00m.dem', 'variables': []}, {'path': 'sims/event_index.0/swmm/hydro.inp', 'variables': ['[SUBCATCHMENTS]', '[JUNCTIONS]', '[OUTFALLS]']}, {'path': 'sims/event_index.0/swmm/hydraulics.inp', 'variables': ['[CONDUITS]', '[JUNCTIONS]', '[POLYGONS]']}, {'path': '../../../../synthetic_test_models/23e859ea50fa19b1/boundary.geojson', 'variables': []}],
        source_paths_rst = '- ``../elevation_10.00m.dem``\n\n- ``sims/event_index.0/swmm/hydro.inp``\n\n  - ``[SUBCATCHMENTS]``\n  - ``[JUNCTIONS]``\n  - ``[OUTFALLS]``\n\n- ``sims/event_index.0/swmm/hydraulics.inp``\n\n  - ``[CONDUITS]``\n  - ``[JUNCTIONS]``\n  - ``[POLYGONS]``\n\n- ``../../../../synthetic_test_models/23e859ea50fa19b1/boundary.geojson``\n',
    log: "logs/plots/system_overview.log"
    conda: "/home/dcl3nd/dev/TRITON-SWMM_toolkit/.claude/worktrees/toolkit_06-13_2259_named-reporting-sets/workflow/envs/triton_swmm.yaml"
    resources: mem_mb=2000, time_min=10
    shell:
        """
        python -m TRITON_SWMM_toolkit.report_renderers._cli system_overview \
            --system-config /home/dcl3nd/.cache/TRITON_SWMM_toolkit/synthetic_test_runs/toolkit_06-13_2259_named-reporting-sets/synth_multi_sim/system_config.yaml \
            --analysis-config /home/dcl3nd/.cache/TRITON_SWMM_toolkit/synthetic_test_runs/toolkit_06-13_2259_named-reporting-sets/synth_multi_sim/analysis_config.yaml \
            --output {output} \
            > {log} 2>&1
        """

def _per_sim_flood_depth_sources(wildcards):
    from TRITON_SWMM_toolkit.report_renderers._figure_emission import (
        collect_per_sim_source_paths,
    )
    return collect_per_sim_source_paths(
        "peak_flood_depth",
        wildcards.event_id,
        rainfall_datavar='RG_synth',
        storm_tide_datavar='water_level',
        dem_rel_path='../elevation_10.00m.dem',
        watershed_rel_path='../../../../synthetic_test_models/23e859ea50fa19b1/watershed.geojson',
    )

def _per_sim_conduit_flow_sources(wildcards):
    from TRITON_SWMM_toolkit.report_renderers._figure_emission import (
        collect_per_sim_source_paths,
    )
    return collect_per_sim_source_paths(
        "conduit_flow",
        wildcards.event_id,
        rainfall_datavar='RG_synth',
        storm_tide_datavar='water_level',
        dem_rel_path='../elevation_10.00m.dem',
        watershed_rel_path='../../../../synthetic_test_models/23e859ea50fa19b1/watershed.geojson',
    )

rule plot_per_sim_peak_flood_depth:
    input:
        consolidated = "_status/e_consolidate_complete.flag",
    output:
        report(
            "plots/per_sim/{event_id}/peak_flood_depth__evt.{event_id}.html",
            caption="report/captions/per_sim_peak_flood_depth.rst",
            category="Per Simulation Results",
            labels={"event_id": "{event_id}", "figure": "Peak flood depth"},
        )
    wildcard_constraints:
        event_id="[A-Za-z0-9_.]+",
    params:
        source_paths = _per_sim_flood_depth_sources,
        source_paths_rst = lambda w: _fmt_sources_rst(_per_sim_flood_depth_sources(w)),
        event_iloc = lambda w: ILOC_BY_EVENT_ID[w.event_id],
    log: "logs/plots/per_sim_peak_flood_depth_{event_id}.log"
    conda: "/home/dcl3nd/dev/TRITON-SWMM_toolkit/.claude/worktrees/toolkit_06-13_2259_named-reporting-sets/workflow/envs/triton_swmm.yaml"
    resources: mem_mb=4000, time_min=15
    shell:
        """
        python -m TRITON_SWMM_toolkit.report_renderers._cli per_sim_peak_flood_depth \
            --system-config /home/dcl3nd/.cache/TRITON_SWMM_toolkit/synthetic_test_runs/toolkit_06-13_2259_named-reporting-sets/synth_multi_sim/system_config.yaml \
            --analysis-config /home/dcl3nd/.cache/TRITON_SWMM_toolkit/synthetic_test_runs/toolkit_06-13_2259_named-reporting-sets/synth_multi_sim/analysis_config.yaml \
            --event-iloc {params.event_iloc} \
            --output {output} \
            > {log} 2>&1
        """

rule plot_per_sim_conduit_flow:
    input:
        consolidated = "_status/e_consolidate_complete.flag",
    output:
        report(
            "plots/per_sim/{event_id}/conduit_flow__evt.{event_id}.html",
            caption="report/captions/per_sim_conduit_flow.rst",
            category="Per Simulation Results",
            labels={"event_id": "{event_id}", "figure": "Conduit flow"},
        )
    wildcard_constraints:
        event_id="[A-Za-z0-9_.]+",
    params:
        source_paths = _per_sim_conduit_flow_sources,
        source_paths_rst = lambda w: _fmt_sources_rst(_per_sim_conduit_flow_sources(w)),
        event_iloc = lambda w: ILOC_BY_EVENT_ID[w.event_id],
    log: "logs/plots/per_sim_conduit_flow_{event_id}.log"
    conda: "/home/dcl3nd/dev/TRITON-SWMM_toolkit/.claude/worktrees/toolkit_06-13_2259_named-reporting-sets/workflow/envs/triton_swmm.yaml"
    resources: mem_mb=4000, time_min=15
    shell:
        """
        python -m TRITON_SWMM_toolkit.report_renderers._cli per_sim_conduit_flow \
            --system-config /home/dcl3nd/.cache/TRITON_SWMM_toolkit/synthetic_test_runs/toolkit_06-13_2259_named-reporting-sets/synth_multi_sim/system_config.yaml \
            --analysis-config /home/dcl3nd/.cache/TRITON_SWMM_toolkit/synthetic_test_runs/toolkit_06-13_2259_named-reporting-sets/synth_multi_sim/analysis_config.yaml \
            --event-iloc {params.event_iloc} \
            --output {output} \
            > {log} 2>&1
        """

rule plot_per_analysis_summary_table:
    input:
        consolidated = "_status/e_consolidate_complete.flag",
    output:
        report(
            "plots/per_analysis/summary_table.html",
            caption="report/captions/per_analysis_summary_table.rst",
            category="Workflow Status",
            subcategory="Workflow Health Summary",
            labels={"figure": "Summary table"},
        )
    params:
        source_paths = [{'path': 'sims/event_index.0/out_tritonswmm/swmm/hydraulics.rpt', 'variables': ['Flow Routing Continuity error (%)']}, {'path': 'sims/event_index.1/out_tritonswmm/swmm/hydraulics.rpt', 'variables': ['Flow Routing Continuity error (%)']}, {'path': 'sims/event_index.2/out_tritonswmm/swmm/hydraulics.rpt', 'variables': ['Flow Routing Continuity error (%)']}],
        source_paths_rst = '- ``sims/event_index.0/out_tritonswmm/swmm/hydraulics.rpt``\n\n  - ``Flow Routing Continuity error (%)``\n\n- ``sims/event_index.1/out_tritonswmm/swmm/hydraulics.rpt``\n\n  - ``Flow Routing Continuity error (%)``\n\n- ``sims/event_index.2/out_tritonswmm/swmm/hydraulics.rpt``\n\n  - ``Flow Routing Continuity error (%)``\n',
    log: "logs/plots/per_analysis_summary_table.log"
    conda: "/home/dcl3nd/dev/TRITON-SWMM_toolkit/.claude/worktrees/toolkit_06-13_2259_named-reporting-sets/workflow/envs/triton_swmm.yaml"
    resources: mem_mb=2000, time_min=5
    shell:
        """
        python -m TRITON_SWMM_toolkit.report_renderers._cli per_analysis_summary \
            --system-config /home/dcl3nd/.cache/TRITON_SWMM_toolkit/synthetic_test_runs/toolkit_06-13_2259_named-reporting-sets/synth_multi_sim/system_config.yaml \
            --analysis-config /home/dcl3nd/.cache/TRITON_SWMM_toolkit/synthetic_test_runs/toolkit_06-13_2259_named-reporting-sets/synth_multi_sim/analysis_config.yaml \
            --output {output} \
            > {log} 2>&1
        """

rule plot_scenario_status_appendix:
    input:
        "scenario_status.csv",
        consolidated = "_status/e_consolidate_complete.flag",
    output:
        report(
            "plots/appendix/scenario_status.html",
            caption="report/captions/scenario_status_appendix.rst",
            category="Appendix",
            subcategory="Scenario Status",
            labels={"figure": "Per-scenario status table"},
        )
    params:
        source_paths = [{'path': 'scenario_status.csv', 'variables': ['event_id', 'model_type', 'status', 'runtime_s', 'continuity_error_pct', 'notes']}],
        source_paths_rst = '- ``scenario_status.csv``\n\n  - ``event_id``\n  - ``model_type``\n  - ``status``\n  - ``runtime_s``\n  - ``continuity_error_pct``\n  - ``notes``\n',
    log: "logs/plots/scenario_status_appendix.log"
    conda: "/home/dcl3nd/dev/TRITON-SWMM_toolkit/.claude/worktrees/toolkit_06-13_2259_named-reporting-sets/workflow/envs/triton_swmm.yaml"
    resources: mem_mb=1000, time_min=5
    shell:
        """
        python -m TRITON_SWMM_toolkit.report_renderers._cli scenario_status_appendix \
            --system-config /home/dcl3nd/.cache/TRITON_SWMM_toolkit/synthetic_test_runs/toolkit_06-13_2259_named-reporting-sets/synth_multi_sim/system_config.yaml \
            --analysis-config /home/dcl3nd/.cache/TRITON_SWMM_toolkit/synthetic_test_runs/toolkit_06-13_2259_named-reporting-sets/synth_multi_sim/analysis_config.yaml \
            --output {output} \
            > {log} 2>&1
        """

rule plot_errors_and_warnings:
    input:
        "scenario_status.csv",
        consolidated = "_status/e_consolidate_complete.flag",
    output:
        report(
            "plots/errors_and_warnings/validation_report.html",
            caption="report/captions/errors_and_warnings.rst",
            category="Errors and Warnings",
            subcategory="Validation Report",
            labels={"figure": "Validation report"},
        )
    params:
        source_paths = [{'path': 'scenario_status.csv', 'variables': ['scenario_setup', 'run_completed', 'actual_nTasks', 'actual_omp_threads', 'actual_total_gpus', 'actual_gpu_backend']}, {'path': 'sims/<event_id>/log_<model_type>.json', 'variables': ['simulation_completed (per scenario × model_type)']}, {'path': '../system_log.json', 'variables': ['compilation_successful', 'compilation_triton_only_successful', 'compilation_swmm_successful']}],
        source_paths_rst = '- ``scenario_status.csv``\n\n  - ``scenario_setup``\n  - ``run_completed``\n  - ``actual_nTasks``\n  - ``actual_omp_threads``\n  - ``actual_total_gpus``\n  - ``actual_gpu_backend``\n\n- ``sims/<event_id>/log_<model_type>.json``\n\n  - ``simulation_completed (per scenario × model_type)``\n\n- ``../system_log.json``\n\n  - ``compilation_successful``\n  - ``compilation_triton_only_successful``\n  - ``compilation_swmm_successful``\n',
    log: "logs/plots/errors_and_warnings.log"
    conda: "/home/dcl3nd/dev/TRITON-SWMM_toolkit/.claude/worktrees/toolkit_06-13_2259_named-reporting-sets/workflow/envs/triton_swmm.yaml"
    resources: mem_mb=1000, time_min=5
    shell:
        """
        python -m TRITON_SWMM_toolkit.report_renderers._cli errors_and_warnings \
            --system-config /home/dcl3nd/.cache/TRITON_SWMM_toolkit/synthetic_test_runs/toolkit_06-13_2259_named-reporting-sets/synth_multi_sim/system_config.yaml \
            --analysis-config /home/dcl3nd/.cache/TRITON_SWMM_toolkit/synthetic_test_runs/toolkit_06-13_2259_named-reporting-sets/synth_multi_sim/analysis_config.yaml \
            --output {output} \
            > {log} 2>&1
        """

rule plot_disk_utilization:
    input:
        consolidated = "_status/e_consolidate_complete.flag",
    output:
        report(
            "plots/disk_utilization.html",
            caption="report/captions/disk_utilization.rst",
            category="System Information",
            labels={"figure": "Disk Utilization"},
        )
    params:
        source_paths = [{'path': '_status/_du.json', 'variables': ['disk_utilization_bytes', 'sub_path_breakdown']}],
        source_paths_rst = '- ``_status/_du.json``\n\n  - ``disk_utilization_bytes``\n  - ``sub_path_breakdown``\n',
    log: "logs/plots/disk_utilization.log"
    conda: "/home/dcl3nd/dev/TRITON-SWMM_toolkit/.claude/worktrees/toolkit_06-13_2259_named-reporting-sets/workflow/envs/triton_swmm.yaml"
    resources: mem_mb=1000, time_min=5
    shell:
        """
        python -m TRITON_SWMM_toolkit.report_renderers._cli disk_utilization \
            --system-config /home/dcl3nd/.cache/TRITON_SWMM_toolkit/synthetic_test_runs/toolkit_06-13_2259_named-reporting-sets/synth_multi_sim/system_config.yaml \
            --analysis-config /home/dcl3nd/.cache/TRITON_SWMM_toolkit/synthetic_test_runs/toolkit_06-13_2259_named-reporting-sets/synth_multi_sim/analysis_config.yaml \
            --output {output} \
            > {log} 2>&1
        """

localrules: export_scenario_status

rule export_scenario_status:
    input: "_status/e_consolidate_complete.flag"
    output:
        csv = "scenario_status.csv",
        md  = "workflow_summary.md",
    log: "/home/dcl3nd/.cache/TRITON_SWMM_toolkit/synthetic_test_runs/toolkit_06-13_2259_named-reporting-sets/synth_multi_sim/synth_multi_sim/logs/export_scenario_status.log"
    conda: "/home/dcl3nd/dev/TRITON-SWMM_toolkit/.claude/worktrees/toolkit_06-13_2259_named-reporting-sets/workflow/envs/triton_swmm.yaml"
    resources:
        slurm_partition="None",
        runtime=10,
        tasks=1,
        cpus_per_task=1,
        mem_mb=1000,
        nodes=1
    shell:
        """
        /home/dcl3nd/miniconda3/envs/triton_swmm_toolkit/bin/python -m TRITON_SWMM_toolkit.export_scenario_status \
            --system-config /home/dcl3nd/.cache/TRITON_SWMM_toolkit/synthetic_test_runs/toolkit_06-13_2259_named-reporting-sets/synth_multi_sim/system_config.yaml \
            --analysis-config /home/dcl3nd/.cache/TRITON_SWMM_toolkit/synthetic_test_runs/toolkit_06-13_2259_named-reporting-sets/synth_multi_sim/analysis_config.yaml \
            > {log} 2>&1
        """

rule render_report:
    input:
        "plots/system_overview.html",
        expand("plots/per_sim/{event_id}/peak_flood_depth__evt.{event_id}.html", event_id=SIM_IDS),
        expand("plots/per_sim/{event_id}/conduit_flow__evt.{event_id}.html", event_id=SIM_IDS),
        "plots/per_analysis/summary_table.html",
        "plots/appendix/scenario_status.html",
        "plots/errors_and_warnings/validation_report.html",
        "plots/disk_utilization.html",
        "scenario_status.csv",
    output:
        "analysis_report.{format}"
    wildcard_constraints:
        format="zip|html"
    log: "/home/dcl3nd/.cache/TRITON_SWMM_toolkit/synthetic_test_runs/toolkit_06-13_2259_named-reporting-sets/synth_multi_sim/synth_multi_sim/logs/render_report_{format}.log"
    resources:
        slurm_partition="None",
        runtime=30,
        tasks=1,
        cpus_per_task=1,
        mem_mb=2000,
        nodes=1
    shell:
        """
        /home/dcl3nd/miniconda3/envs/triton_swmm_toolkit/bin/python -m TRITON_SWMM_toolkit.render_report_runner \
            --system-config /home/dcl3nd/.cache/TRITON_SWMM_toolkit/synthetic_test_runs/toolkit_06-13_2259_named-reporting-sets/synth_multi_sim/system_config.yaml \
            --analysis-config /home/dcl3nd/.cache/TRITON_SWMM_toolkit/synthetic_test_runs/toolkit_06-13_2259_named-reporting-sets/synth_multi_sim/analysis_config.yaml \
            --format {wildcards.format} \
            > {log} 2>&1
        """
