"""Render the permanent profile-results Markdown doc from RunArtifacts.

Statistical-reporting discipline: median + IQR everywhere. Mean and stddev are
intentionally NOT used at any rollup site. Heavy-tailed laptop noise
(background apps, GC pauses, frequency scaling, thermal throttling, page-cache
state) does not produce a Gaussian residual distribution; mean+stddev under
that noise reports a centroid biased toward the tail and a "standard deviation"
that satisfies none of its textbook properties. References:
Mytkowicz et al. ASPLOS 2009; Hager-Wellein 2011 §8.3.

Determinism contract (R-DET): the set of H2/H3 headings, the column headers
of every table, the sorted corpus-inventory nodeid set, and the structural
ordering of tables (tests by wall-clock desc, hot functions by cumulative
time desc, rules by wall-clock desc) are byte-identical across runs at the
same SHA. Numerical wall-clock / cumulative-time values are run-to-run
variant and excluded from V-DET's structural diff.
"""

from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from statistics import median, quantiles
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from scripts.profile.profile_routine_tests import RunArtifacts

_ARCHIVE_SUBDIR = "previous_run_archives"


@dataclass
class _SnakemakeRollup:
    """Per-(rule, origin) accumulator for cross-rep median rollup."""
    job_count: int
    total_s: float
    mean_s: float
    min_s: float
    max_s: float
    zero_jobs: int
    normalized: str


def _aggregate(values: list[float]) -> tuple[float, float, float]:
    """Return (median, p25, p75) using interpolated quartiles for N>=3; p25=p75=median otherwise.

    Uses statistics.quantiles(..., n=4, method='exclusive') for textbook quartile
    interpolation rather than integer-index approximation, eliminating small-N bias
    in the IQR computation.
    """
    if not values:
        return 0.0, 0.0, 0.0
    if len(values) < 3:
        m = median(values)
        return m, m, m
    qs = quantiles(sorted(values), n=4, method="exclusive")
    return median(values), qs[0], qs[2]


def _fingerprint_hash(env_fingerprint: dict[str, str]) -> str:
    """Short SHA-256 prefix of the canonical env-fingerprint JSON.

    Used to content-address previous-run archives so two contributors on two
    machines can refresh the doc without overwriting each other's history.
    """
    canonical = json.dumps(env_fingerprint, sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()[:12]


def _archive_previous_run(output_path: Path, fingerprint_sha: str) -> Path | None:
    """Move the prior output to previous_run_archives/{sha}_{utc}.md, return its path."""
    if not output_path.exists():
        return None
    prior = output_path.read_text()
    if not prior.strip() or "Initial placeholder" in prior:
        return None
    archive_dir = output_path.parent / _ARCHIVE_SUBDIR
    archive_dir.mkdir(parents=True, exist_ok=True)
    stamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    target = archive_dir / f"{fingerprint_sha}_{stamp}.md"
    target.write_text(prior)
    return target


def emit(
    *,
    env_fingerprint: dict[str, str],
    runs: list["RunArtifacts"],
    top_n: int,
    findings_top_k: int,
    output_path: Path,
) -> None:
    """Write the deterministic profile-results doc to output_path (overwritten)."""
    output_path.parent.mkdir(parents=True, exist_ok=True)
    fingerprint_sha = _fingerprint_hash(env_fingerprint)
    archive_path = _archive_previous_run(output_path, fingerprint_sha)

    if not runs:
        output_path.write_text(_render_empty(env_fingerprint))
        return
    primary = runs[0]

    lines: list[str] = []
    # Frontmatter (substrate-output type)
    lines.append("---")
    lines.append("knowledge_doc_type: substrate_code")
    lines.append("auto_generated: true")
    lines.append("generated_by: scripts/profile/profile_routine_tests.py")
    lines.append(f"env_fingerprint_sha: {fingerprint_sha}")
    lines.append("---")
    lines.append("")
    lines.append("# Routine Test Profile Results")
    lines.append("")
    lines.append(
        "Auto-generated by `python -m scripts.profile.profile_routine_tests`. "
        "Do not edit by hand — re-run the command to refresh."
    )
    lines.append("")

    # Optimization preamble (Bailey 2011 §10.3; estimate cost before profiling).
    lines.append(
        "> **How to use this doc for an optimization plan.** The Findings A "
        "table below names the top cost centers in the corpus by share of "
        "total wall-clock. Treat the top 3 as your candidate set, not as a "
        "directive. Before proposing any optimization, do a Roofline-class "
        "back-of-envelope: is the cost in fixture setup (caching / "
        "fixture-scope changes), in test bodies (kernel-level work that may "
        "be a memory or I/O bound), or in subprocess fork-and-wait (Snakemake "
        "/ pyswmm spawns)? This doc is wall-clock attribution, not "
        "bottleneck-mechanism analysis — the mechanism question requires a "
        "separate per-cost-center investigation."
    )
    lines.append("")

    # Environment fingerprint
    lines.append("## Environment Fingerprint")
    lines.append("")
    for k in sorted(env_fingerprint):
        v = env_fingerprint[k]
        if "\n" in v:
            lines.append(f"- **{k}**:")
            lines.append("")
            lines.append("    ```")
            for ln in v.splitlines():
                lines.append(f"    {ln}")
            lines.append("    ```")
        else:
            lines.append(f"- **{k}**: `{v}`")
    lines.append(f"- **repetitions_retained**: `{len(runs)}`")
    if archive_path is not None:
        lines.append(f"- **previous_run_archive**: `{archive_path.relative_to(output_path.parent)}`")
    lines.append("")

    # Out of Scope (Bailey 2011 §1.4 — name what this measurement does not cover).
    lines.append("## Out of Scope")
    lines.append("")
    lines.append("- **GPU work**: the routine corpus is CPU-only; GPU-marked tests are excluded.")
    lines.append("- **HPC-only paths**: `test_frontier_*`, `test_UVA_*`, `test_PILOT_*` are slow-marked and excluded.")
    lines.append("- **Memory cost**: this is wall-clock attribution only; no `tracemalloc` or RSS tracking.")
    lines.append("- **I/O cost per storage tier**: wall-clock only; no per-syscall attribution.")
    lines.append("- **Concurrent-test contention**: runs single-threaded with `-p no:xdist`.")
    lines.append("")

    # Pre-flight Soft-Recommendations (Bailey 2011 §1.4 — disclose configuration discipline).
    lines.append("## Pre-flight Soft-Recommendations")
    lines.append("")
    lines.append(
        "These are optional disciplines that lower the noise floor without being "
        "required. The defaults work for `--repetitions 1` doc refresh; consider "
        "applying these when running `--repetitions >= 3` for measurement work."
    )
    lines.append("")
    lines.append("- Set CPU governor to performance: `sudo cpupower frequency-set -g performance`")
    lines.append("- Close background browser/IDE windows competing for the SMT sibling core.")
    lines.append("- Pin to a single physical core: prefix the profile command with `taskset -c 0`.")
    lines.append("")

    # Corpus inventory
    lines.append("## Corpus Inventory")
    lines.append("")
    lines.append("| Node ID | Status | Error |")
    lines.append("|---|---|---|")
    for entry in sorted(primary.corpus, key=lambda e: e.nodeid):
        err = (entry.error or "").replace("|", "\\|")
        lines.append(f"| `{entry.nodeid}` | {entry.status} | {err} |")
    lines.append("")

    # Per-test wall-clock (authoritative — pytest plugin hook data)
    lines.append("## Per-Test Wall-Clock")
    lines.append("")
    lines.append(
        "**Wall-clock attribution (authoritative — pytest `pytest_runtest_logreport` "
        "setup/call/teardown durations).** Median across kept reps. The "
        "`child_cpu_s` column surfaces cProfile-invisible subprocess CPU "
        "(pyswmm fork-spawn per Architecture Gotcha #3); large values indicate "
        "work that the Hot Functions table cannot attribute."
    )
    lines.append("")
    iqr_enabled = len(runs) >= 3
    if iqr_enabled:
        lines.append(
            "| Node ID | Setup (s) | Setup IQR (s) | Call (s) | Call IQR (s) | "
            "Teardown (s) | Teardown IQR (s) | Total (s, median) | Total IQR (s) | "
            "Child CPU (s) | Outlier flag | Outcome |"
        )
        lines.append("|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|:---:|:---:|")
    else:
        lines.append("| Node ID | Setup (s) | Call (s) | Teardown (s) | Total (s, median) | Child CPU (s) | Outlier flag | Outcome |")
        lines.append("|---|---:|---:|---:|---:|---:|:---:|:---:|")
    all_nodeids = sorted({n for r in runs for n in r.per_test})
    setup_medians: list[float] = []
    rows: list[tuple[str, float, float, float, float, float, float, float, float, float, str]] = []
    for nid in all_nodeids:
        per_rep = [r.per_test[nid] for r in runs if nid in r.per_test]
        if not per_rep:
            continue
        s_med, s_p25, s_p75 = _aggregate([p.setup_s for p in per_rep])
        c_med, c_p25, c_p75 = _aggregate([p.call_s for p in per_rep])
        t_med, t_p25, t_p75 = _aggregate([p.teardown_s for p in per_rep])
        tot_med, tot_p25, tot_p75 = _aggregate([p.total_s for p in per_rep])
        cpu_med, _, _ = _aggregate([p.child_cpu_seconds for p in per_rep])
        rows.append((
            nid, s_med, s_p75 - s_p25, c_med, c_p75 - c_p25,
            t_med, t_p75 - t_p25, tot_med, tot_p75 - tot_p25, cpu_med, per_rep[0].outcome,
        ))
        setup_medians.append(s_med)
    setup_population_median = median(setup_medians) if setup_medians else 0.0
    rows.sort(key=lambda r: r[7], reverse=True)
    for nid, s, s_iqr, c, c_iqr, t, t_iqr, tot, tot_iqr, cpu, outcome in rows:
        outlier = "!" if (setup_population_median > 0 and s > 2 * setup_population_median) else ""
        if iqr_enabled:
            lines.append(
                f"| `{nid}` | {s:.3f} | {s_iqr:.3f} | {c:.3f} | {c_iqr:.3f} | "
                f"{t:.3f} | {t_iqr:.3f} | {tot:.3f} | {tot_iqr:.3f} | "
                f"{cpu:.3f} | {outlier} | {outcome} |"
            )
        else:
            lines.append(
                f"| `{nid}` | {s:.3f} | {c:.3f} | {t:.3f} | {tot:.3f} | {cpu:.3f} | {outlier} | {outcome} |"
            )
    lines.append("")

    # Per-fixture wall-clock
    lines.append("## Per-Fixture Wall-Clock")
    lines.append("")
    lines.append("| Fixture | Scope | Duration (s, median) | First consumer |")
    lines.append("|---|---|---:|---|")
    fixture_acc: dict[tuple[str, str], tuple[list[float], str]] = {}
    for r in runs:
        for f in r.fixtures:
            key = (f.name, f.scope)
            durations, first_consumer = fixture_acc.get(key, ([], f.consumer_nodeid))
            durations.append(f.duration_s)
            fixture_acc[key] = (durations, first_consumer)
    for (name, scope), (durations, consumer) in sorted(
        fixture_acc.items(), key=lambda kv: (-median(kv[1][0]), kv[0])
    ):
        lines.append(f"| `{name}` | {scope} | {median(durations):.3f} | `{consumer}` |")
    lines.append("")

    # Collection phase + conftest import-cost
    lines.append("## Collection Phase")
    lines.append("")
    coll_times = [r.collection_total_s for r in runs]
    lines.append(f"Total collection wall-clock (median): **{median(coll_times):.3f} s**")
    lines.append("")
    lines.append("### Conftest Import Cost")
    lines.append("")
    lines.append("| Conftest | Self time (s, median) |")
    lines.append("|---|---:|")
    conftest_keys = sorted({k for r in runs for k in r.conftest_import_times})
    conftest_rows = [
        (k, median([r.conftest_import_times.get(k, 0.0) for r in runs]))
        for k in conftest_keys
    ]
    for k, v in sorted(conftest_rows, key=lambda kv: (-kv[1], kv[0])):
        lines.append(f"| `{k}` | {v:.3f} |")
    lines.append("")

    # Snakemake per-rule breakdown + diagnostics
    lines.append("## Snakemake Per-Rule Breakdown")
    lines.append("")
    diag = primary.snakemake_diagnostics
    lines.append(
        f"- Snakefiles found: **{diag.snakefiles_found}** "
        f"({diag.snakefiles_with_metadata} with metadata, "
        f"{diag.snakefiles_dry_run_only} dry-run-only, "
        f"{diag.snakefiles_zero_records} zero-record)"
    )
    lines.append(f"- Total metadata records: **{diag.total_records}**")
    if diag.parser_warnings:
        lines.append("- Parser warnings:")
        for w in sorted(set(diag.parser_warnings)):
            lines.append(f"    - {w}")
    lines.append("")
    lines.append("| Rule (verbatim) | Rule (normalized) | Jobs | Total (s) | Mean (s) | Min (s) | Max (s) | Zero-duration jobs | Origin |")
    lines.append("|---|---|---:|---:|---:|---:|---:|---:|---|")
    sm_acc: dict[tuple[str, str], list[_SnakemakeRollup]] = {}
    for r in runs:
        for sr in r.snakemake_rules:
            sm_acc.setdefault((sr.rule, sr.test_origin), []).append(
                _SnakemakeRollup(
                    job_count=sr.job_count, total_s=sr.total_s, mean_s=sr.mean_s,
                    min_s=sr.min_s, max_s=sr.max_s,
                    zero_jobs=sr.zero_duration_job_count, normalized=sr.rule_normalized,
                )
            )
    sm_sorted = sorted(
        sm_acc.items(),
        key=lambda kv: (-median([row.total_s for row in kv[1]]), kv[0]),
    )
    for (rule, origin), rollups in sm_sorted:
        med_total = median([d.total_s for d in rollups])
        med_mean = median([d.mean_s for d in rollups])
        med_min = median([d.min_s for d in rollups])
        med_max = median([d.max_s for d in rollups])
        jobs = max(d.job_count for d in rollups)
        zero_jobs = max(d.zero_jobs for d in rollups)
        normalized = rollups[0].normalized
        lines.append(
            f"| `{rule}` | `{normalized}` | {jobs} | {med_total:.3f} | "
            f"{med_mean:.3f} | {med_min:.3f} | {med_max:.3f} | {zero_jobs} | `{origin}` |"
        )
    if not sm_sorted:
        lines.append("| _(no Snakemake metadata harvested in this run)_ |  |  |  |  |  |  |  |  |")
    lines.append("")

    # Hot functions (cProfile, global; instrumentation-tainted wall-clock disclaimer)
    lines.append("## Top Hot Functions (cProfile, global)")
    lines.append("")
    lines.append(
        "**Per-function attribution (cProfile, in-process Python frames only — "
        "cumulative-time values include cProfile's ~25-30% instrumentation "
        "overhead and are NOT a wall-clock authority).** The wall-clock authority "
        "is the Per-Test Wall-Clock table above."
    )
    lines.append("")
    lines.append("| Function | Cumulative time (s) | N calls |")
    lines.append("|---|---:|---:|")
    for label, ct, nc in primary.global_hot_functions[:top_n]:
        lines.append(f"| `{label}` | {ct:.3f} | {nc} |")
    if not primary.global_hot_functions:
        lines.append("| _(no cProfile data — pass not run or pstats empty)_ |  |  |")
    lines.append("")

    # Findings — two views (A: share of total wall-clock; B: zero-duration job count)
    lines.append("## Findings")
    lines.append("")
    total_corpus_wallclock = sum(rec.total_s for rec in primary.per_test.values())
    lines.append(
        f"Total corpus wall-clock (median across kept reps): "
        f"**{total_corpus_wallclock:.3f} s**."
    )
    lines.append("")

    # Findings A
    findings_a: list[tuple[str, float, int, str]] = []
    fixture_totals: dict[str, list[float]] = {}
    for r in runs:
        for f in r.fixtures:
            fixture_totals.setdefault(f.name, []).append(f.duration_s)
    for name, durs in fixture_totals.items():
        findings_a.append((f"fixture `{name}`", median(durs), 1, "fixture"))
    for (rule, origin), rollups in sm_acc.items():
        med_total = median([d.total_s for d in rollups])
        findings_a.append((
            f"snakemake rule `{rule}` @ `{origin}`",
            med_total, rollups[0].job_count, "rule",
        ))
    for label, ct, nc in primary.global_hot_functions[:findings_top_k]:
        findings_a.append((f"function `{label}`", ct, nc, "function"))
    findings_a.sort(key=lambda f: (-f[1], f[0]))
    lines.append("### Findings A — top cost centers by share of total wall-clock")
    lines.append("")
    lines.append("| Rank | Cost center | Share (s, median) | Share (%) | Count | Kind |")
    lines.append("|---:|---|---:|---:|---:|---|")
    for rank, (label, share, count, kind) in enumerate(findings_a[:findings_top_k], start=1):
        pct = (share / total_corpus_wallclock * 100.0) if total_corpus_wallclock else 0.0
        lines.append(f"| {rank} | {label} | {share:.3f} | {pct:.1f}% | {count} | {kind} |")
    if not findings_a:
        lines.append("| 1 | _(no cost centers identified)_ |  |  |  |  |")
    lines.append("")

    # Findings B — zero-duration job count (catches sub-second Snakemake rules
    # dropped from view A by mtime-resolution limits)
    lines.append("### Findings B — top rules by zero-duration job count")
    lines.append("")
    lines.append(
        "Sub-second Snakemake rules may report `endtime - starttime == 0` on "
        "filesystems with second-resolution mtime. These rules drop out of "
        "Findings A but may dominate by aggregate job count."
    )
    lines.append("")
    lines.append("| Rank | Rule | Zero-duration jobs | Total jobs | Origin |")
    lines.append("|---:|---|---:|---:|---|")
    b_rows: list[tuple[str, int, int, str]] = []
    for (rule, origin), rollups in sm_acc.items():
        zero_jobs = max(d.zero_jobs for d in rollups)
        total_jobs = max(d.job_count for d in rollups)
        if zero_jobs > 0:
            b_rows.append((rule, zero_jobs, total_jobs, origin))
    b_rows.sort(key=lambda r: (-r[1], r[0]))
    for rank, (rule, zero, total, origin) in enumerate(b_rows[:findings_top_k], start=1):
        lines.append(f"| {rank} | `{rule}` | {zero} | {total} | `{origin}` |")
    if not b_rows:
        lines.append("| 1 | _(no zero-duration rules observed)_ |  |  |  |")
    lines.append("")

    # Timing sample (per-rep totals; this is the "what numbers landed this run" appendix)
    lines.append("## Timing Sample (this run)")
    lines.append("")
    lines.append(f"- repetitions = {len(runs)}")
    lines.append("")
    for i, r in enumerate(runs):
        lines.append(f"### Run {i + 1}")
        lines.append("")
        total = sum(rec.total_s for rec in r.per_test.values())
        lines.append(f"- corpus wall-clock total: {total:.3f} s")
        lines.append(f"- collection wall-clock: {r.collection_total_s:.3f} s")
        if r.pyspy_speedscope_path is not None:
            lines.append(f"- py-spy speedscope: `{r.pyspy_speedscope_path}`")
        if r.cprofile_pstats_path is not None:
            lines.append(f"- cProfile pstats: `{r.cprofile_pstats_path}`")
        lines.append("")

    if archive_path is not None:
        lines.append("## Previous Run Archive")
        lines.append("")
        lines.append(
            f"Previous output preserved at `{archive_path.relative_to(output_path.parent)}` "
            "(content-addressed by env-fingerprint SHA + UTC timestamp). Earlier "
            "history beyond the immediately-prior run is not retained automatically — "
            "the archive directory grows monotonically; prune by hand if needed."
        )
        lines.append("")

    output_path.write_text("\n".join(lines))


def _render_empty(env_fingerprint: dict[str, str]) -> str:
    """Render a minimal doc when no runs completed (e.g., all profiling disabled)."""
    return (
        "---\n"
        "knowledge_doc_type: substrate_code\n"
        "auto_generated: true\n"
        "generated_by: scripts/profile/profile_routine_tests.py\n"
        "---\n\n"
        "# Routine Test Profile Results\n\n"
        "> No profile runs completed. Re-run with `--pyspy` and/or `--cprofile` enabled.\n"
    )
